services:
  mongodb:
    image: mongo:latest
    command: ["--replSet", "rs0"]
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./script.js:/docker-entrypoint-initdb.d/script.js

volumes:
  mongodb_data:
